config/routes.rb
Rails.application.routes.draw do
  resources :lab_reports do
    resources :marks
  end

  root 'lab_reports#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lab_report.rb
class LabReport < ApplicationRecord
  has_one :mark
  validates :title, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 500 }
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :lab_report
  validates :points, presence: true, inclusion: { in: 0..100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lab_reports_controller.rb
class LabReportsController < ApplicationController
  def index
    @lab_report = LabReport.all
  end

  def show
    @lab_report = LabReport.find(params[:id])
  end

  def new
    @lab_report = LabReport.new
  end

  def create
    @lab_report = LabReport.new(lab_report_params)

    if @lab_report.save
      redirect_to @lab_report, flash: { success: 'LabReport was added' }
    else
      render 'new', flash: { success: 'Some error occured' }
    end
  end

  def edit
    @lab_report = LabReport.find(params[:id])
  end

  def update
    @lab_report = LabReport.find(params[:id])
    @lab_report.update(lab_report_params)
    redirect_to @lab_report, flash: { success: 'LabReport was updated' }
  end

  def destroy
    @lab_report = LabReport.find(params[:id])
    @lab_report.destroy
    redirect_to action: :index
  end

  private

  def lab_report_params
    params.require(:lab_report).permit(:title, :description)
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :get_report

  def create
    get_report

    mark_letter = get_mark

    @mark = @lab_report.build_mark(points: mark_letter[:mark], letter: mark_letter[:letter])

    if @mark.save
      redirect_to '/'
    else
      render 'new'
    end
  end

  def index
    @mark = Mark.all
  end

  def show
    @mark = Mark.find(params[:id])
  end

  def new
    @mark = Mark.new
  end

  def destroy
    @lab_report = LabReport.find(params[:lab_report_id])

    @mark = @lab_report.mark.destroy

    @mark.destroy

    redirect_to '/'
  end

  private

  def convert_to_letter(mark)
    case mark
    when 90..100
      'A'
    when 80..89
      'B'
    when 65..79
      'C'
    when 55..64
      'D'
    when 50..54
      'E'
    when 1..49
      'F'
    else
      'Error: No Mark'
    end
  end

  def get_mark
    hash = params.require(:mark).permit(:points)

    if hash[:points] != ''
      mark_int = hash[:points].to_i

      mark_letter = convert_to_letter(mark_int)

      hash = { mark: mark_int, letter: mark_letter }
    else
      mark_int = nil

      mark_letter = nil
    end

    { mark: mark_int, letter: mark_letter }
  end

  def get_report
    @lab_report = LabReport.find(params[:lab_report_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/lab_reports_helper.rb
module LabReportsHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/lab_reports/_form.html.erb
<%= form_with model: @lab_report do |f| %>
<% if @lab_report .errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@lab_report .errors.count, "error") %>
      prohibited this lab_report  from being saved:</h2>
    <ul>
      <% lab_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div style=" padding-left: 700px; ">
<div class="form-group;">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</div>

<div class="actions">
  <%= f.submit :Save %>
  <%= button_to 'Show', @lab_report  %>
</div>
</div>
<% end %>

app/views/lab_reports/edit.html.erb
<h1 style="text-align:center;padding-top: 50px">Editing lab_reports </h1>
<%= render 'form', lab: @lab_report %>

app/views/lab_reports/index.html.erb
<h1 style="text-align:center">
  Labs reports
</h1>

<div style=" padding-left: 150px; padding-right: 150px; ">
  <%= button_to 'Add report', new_lab_report_path,:method => :get, class: 'btn btn-primary ' %>

    <% @lab_report.each do |item|%>
      <h3>
        <%= item.title%>
      </h3>
      
      <p>
        <%= item.description%>
      </p>
      
    
<% if item.errors.any? %>
      <% item.errors.full_messages.each do |msg| %>
        <div class= "center">
          <%= msg%>
          </div>
      <% end %>
    <% end %>

    <div class="btn-group" role="group" aria-label="Basic example">
    <%if item.mark == nil %>
      </p><%= button_to 'Add mark', new_lab_report_mark_path(item.id),:method => :get, class: 'btn btn-primary ' %>  
    <%else%>
        <%= item.mark.points %>
        <%= "("%>
        <%=item.mark.letter %>
        <%= ")"%>
    <%end%>

    <%if item.mark == nil%>
      <%= button_to 'remove', '/', :method => :get, data: { disable_with: 'There is nothing to remove!' }, class: 'btn btn-success' %>
   <%else%>
      <%= button_to 'remove', lab_report_mark_path(item.id, item.mark.lab_report_id), :method => 'delete',  data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <%end%>
    </div>
  <%end%>
  
</div>

app/views/lab_reports/new.html.erb
<h1 style="text-align:center;padding-top: 50px">Create labs report</h1>
<%= render 'form', lab: @lab_report %>

app/views/lab_reports/show.html.erb
<div style="text-align:center; margin-top: 2%;">
<h1> 
<%= @lab_report.title %> 
</h1>

<p> 
<%= @lab_report.description %> 
</p>

<%=  button_to 'Remove',lab_report_path(@lab_report), method: :delete, class:"btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
<a class="mp-6 text-dark" href="<%= edit_lab_report_path(@lab_report)%>">
<i class="fa fa-pencil "></i>
</a>
<a class="mp-6 text-dark" href="<%= root_path(@lab_report)%>">
<i class="fa fa-hashtag "></i>
</a>
  </div> 
  
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marks/new.html.erb
<div style=" padding-left: 850px; padding-right: 100px; padding-bottom: 200px;padding-top: 200px; ">
  <%= form_for :mark, url: lab_report_marks_path do |f| %>
    <% if @mark.errors.any? %>
      <% @mark.errors.full_messages.each do |msg| %>
        <div class= "form-group ">
          <%= msg%>
      <% end %>
    <% end %>
    <p >Mark <br>
      <%= f.text_field :points%>
    </p>
    <div style="padding-left: 50px; " >
      <%= f.submit :Save %>
      </div>
  <% end %>
</div>